name: waah_frontend
description: POS frontend
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.4.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    flutter_riverpod: ^2.6.1
    go_router: ^16.2.5
    dio: ^5.9.0
    google_fonts: ^6.3.2
    path_provider: ^2.1.5
    path: ^1.9.0
    sqflite: ^2.3.3+1
    sqflite_common_ffi: ^2.3.4
    sqlite3_flutter_libs: ^0.5.24
    http: ^1.5.0
    shared_preferences: ^2.5.3
    file_picker: ^10.3.3
    drift: ^2.16.0
    sqlite3: ^2.4.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    # IMPORTANT: removed flutter_app_name
    flutter_launcher_icons: ^0.14.0
    drift_dev: ^2.16.0
    build_runner: ^2.4.0
flutter:
    uses-material-design: true
    assets:
        - assets/images/
        # make sure your icon is here:
        # - assets/app_icon.png

flutter_launcher_icons:
    android: true
    windows:
        generate: true
        icon_size: 256
    web:
        generate: true
        background_color: "#ffffff"
        theme_color: "#ffffff"
    image_path: "assets/app_icon.png"
